version: '3.8'

services:
  paperless-notion-sync:
    build: .
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - paperless_network

networks:
  paperless_network:
    external: true
    # name: your_paperless_network_name  # Uncomment and change this to match your Paperless network name 